name: Deploy React to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: |
          export CI=false
          npm run build

      - name: Deploy .env file to EC2
        run: |
          echo "Uploading .env file to EC2"
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
          mkdir -p $HOME/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > $HOME/.ssh/stay-with-me-dangsan.pem
          chmod 600 $HOME/.ssh/stay-with-me-dangsan.pem
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> $HOME/.ssh/known_hosts
          scp -i $HOME/.ssh/stay-with-me-dangsan.pem .env ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/var/www/html/.env
          
      - name: Deploy to EC2
        run: |
          echo "EC2 Public IP: ${{ secrets.EC2_PUBLIC_IP }}"
          scp -r -i $HOME/.ssh/stay-with-me-dangsan.pem ./build/* ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/var/www/html/
